### ISSUE TITLE
How to disable mod pans notification to IOS using mod_apns.erl file

### ISSUE THREAD

**Issue by nileshbacancy** [mrDoctorWho/ejabberd_mod_apns#26] opened 2018-09-18 07:09 UTC
Hello @mrDoctorWho @zinid 

How to disable notification in IOS using mod_apns.erl file and I am using mysql database.
We are using below mod_apns.erl file. 

mod_apns.erl - https://github.com/joanlopez/ejabberd-mod-apns/blob/master/src/mod_apns.erl

there is always add notification_enabled = 1 
1) How can I prevent notification if I will change notification_enabled = 0?
2) I am not receiving group chat notification using mod_apns.erl even notification group flag enabled.
 -  notification_group_enabled = 1 
Please help me for 1 and 2 questions.

**Comment by mrDoctorWho** [comment] 2018-10-01 09:47
Closing as duplicate of #27.

**Closed as completed by mrDoctorWho** 2018-10-01 09:47 UTC
